- name: create lgsm group
  group:
    name: "{{ lgsm_group }}"
    system: yes
    state: present
  become: yes

- name: create lgsm user
  user:
    name: "{{ lgsm_user }}"
    groups: "{{ lgsm_group }}"
    system: yes
    append: yes
    shell: /bin/bash
    state: present
    home: "/home/{{ lgsm_user }}"
  become: yes

- name: add multiverse repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu focal multiverse
    state: present
  become: yes

- name: add i386 architecture
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch
  when: ansible_architecture != 'i386'
  become: yes

- name: update cache
  apt:
    update_cache: yes
  become: yes

- name: accept steam license
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"
  become: yes

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - curl
    - wget
    - file
    - tar
    - bzip2
    - gzip
    - unzip
    - bsdmainutils
    - util-linux
    - ca-certificates
    - binutils
    - bc
    - jq
    - tmux
    - netcat
    - lib32gcc1
    - lib32stdc++6
    - steamcmd

- name: download linuxgsm
  get_url:
    url: https://linuxgsm.sh
    dest: "/home/{{ lgsm_user }}/linuxgsm.sh"
    owner: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"
    mode: 0755
  become: yes

- name: run linuxgsm
  command: ./linuxgsm.sh csgoserver
  args:
    chdir: "/home/{{ lgsm_user }}/"
    creates: "/home/{{ lgsm_user }}/csgoserver"
  become: yes
  become_user: "{{ lgsm_user }}"

- name: install csgo server
  command: ./csgoserver ai
  args:
    chdir: "/home/{{ lgsm_user }}/"
    creates: "/home/{{ lgsm_user }}/lgsm/config-lgsm/csgoserver/csgoserver.cfg"
  become: yes
  become_user: "{{ lgsm_user }}"
  notify: restart csgo

- name: add lgsm config
  template:
    src: lgsm.j2
    dest: "/home/{{ lgsm_user }}/lgsm/config-lgsm/csgoserver/csgoserver.cfg"
    owner: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"
    mode: 0640
  become: yes
  notify: restart csgo

- name: add csgo server config
  template:
    src: csgoserver.cfg.j2
    dest: "/home/{{ lgsm_user }}/serverfiles/csgo/cfg/csgoserver.cfg"
    owner: "{{ lgsm_user }}"
    group: "{{ lgsm_group }}"
    mode: 0640
  become: yes
  notify: restart csgo

- name: add systemd unit file
  template:
    src: lgsm-csgo.service.j2
    dest: /etc/systemd/system/lgsm-csgo.service
    mode: 0644
  become: yes
  notify: restart csgo

- name: enable csgo server
  systemd:
    name: lgsm-csgo.service
    enabled: yes
    daemon_reload: yes
  become: yes
